---
swagger: "2.0"
info:
  description: "This is a sample server {{cookiecutter.project_name}} server."
  version: "1.0.0"
  title: "Swagger {{cookiecutter.project_name}}"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
- name: "{{cookiecutter.project_name}}"
  description: "Everything about your {{cookiecutter.project_name}}"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "store"
  description: "Example endpoint  list of {{cookiecutter.project_name}}"
- name: "user"
  description: "Operations about user"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"
schemes:
- "http"
paths:
  /:
    get:
      tags:
      - "Dummy View"
      summary: "Example endpoint return a message"
      description: ""
      operationId: "get"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "A detail view with a message"
          schema:
            $ref: '#/definitions/dummy_msg'
      x-swagger-router-controller: "project.views.views"
    post:
      tags:
      - "Dummy View"
      summary: "Example endpoint return a message"
      description: ""
      operationId: "post"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "A detail view with a message"
          schema:
            $ref: '#/definitions/dummy_msg'
      x-swagger-router-controller: "project.views.views"
definitions:
  dummy_msg:
    type: "object"
    properties:
      msg:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"